import 'package:flutter/material.dart';

/* Rectangle timer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTimerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 202.01422119140625,
      height: 125.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Image.asset(
          "assets/images/f4614a217365cf1d60d29fc13cf161c60850292f.png",
          color: null,
          fit: BoxFit.cover,
          width: 202.01422119140625,
          height: 125.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
