import 'package:flutter/material.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedRectangle3Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedAppdescWidget9.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedCoinWidget1.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedBackWidget5.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedEarncreditsforthehoursyoustudyWidget.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedStudyTimerWidget2.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedGroup4Widget4.dart';
import 'package:flutterapp/new2app/generatedstudytimerwidget1/generated/GeneratedNoun_pause_19482031Widget.dart';

/* Frame Study Timer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStudyTimerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(15.0),
      child: Container(
        width: 411.0,
        height: 823.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(15.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(15.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAppdescWidget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 97.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 80.94116973876953,
                height: 80.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 85.0,
                child: GeneratedRectangle3Widget4(),
              ),
              Positioned(
                left: 347.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 42.44285583496094,
                height: 43.0,
                child: GeneratedGroup4Widget4(),
              ),
              Positioned(
                left: 23.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 48.0,
                child: GeneratedStudyTimerWidget2(),
              ),
              Positioned(
                left: 22.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 72.0,
                child: GeneratedEarncreditsforthehoursyoustudyWidget(),
              ),
              Positioned(
                left: 244.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 33.0,
                child: GeneratedCoinWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedBackWidget5(),
              ),
              Positioned(
                left: 232.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedNoun_pause_19482031Widget(),
              )
            ]),
      ),
    ));
  }
}
